#!/bin/bash

# ========== USAGE ==========
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <SignalSV_output_folder>"
    exit 1
fi

OUTDIR="$1"
HTML="$OUTDIR/SignalSV_dashboard.html"

# ========== START HTML ==========
echo "[+] Generating HTML dashboard: $HTML"
cat <<EOF > "$HTML"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SignalSV Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; background-color: #f9f9f9; }
    h1, h2 { color: #333; }
    img { max-width: 100%; border: 1px solid #ccc; margin-bottom: 20px; }
    .section { padding: 20px; margin-bottom: 40px; background: #fff; border-radius: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th, td { border: 1px solid #ddd; padding: 8px; font-size: 14px; }
    th { background-color: #f2f2f2; }
  </style>
</head>
<body>
<h1>🧬 SignalSV Analysis Report</h1>
EOF

# ========== SECTIONS ==========

# Entropy plot
if [[ -f "$OUTDIR/entropy_plot.png" ]]; then
cat <<EOF >> "$HTML"
<div class="section">
  <h2>Entropy Profile Plot</h2>
  <img src="entropy_plot.png" alt="Entropy Plot">
</div>
EOF
fi

# tSNE
if [[ -f "$OUTDIR/clustered_tsne.png" ]]; then
cat <<EOF >> "$HTML"
<div class="section">
  <h2>t-SNE Visualization</h2>
  <img src="clustered_tsne.png" alt="t-SNE">
</div>
EOF
fi

# Heatmap
if [[ -f "$OUTDIR/clustered_heatmap.png" ]]; then
cat <<EOF >> "$HTML"
<div class="section">
  <h2>Entropy Heatmap</h2>
  <img src="clustered_heatmap.png" alt="Heatmap">
</div>
EOF
fi

# Cluster Summary Table
if [[ -f "$OUTDIR/clustered_cluster_summary.tsv" ]]; then
cat <<EOF >> "$HTML"
<div class="section">
  <h2>Cluster Summary</h2>
  <table>
    <tr><th>Cluster</th><th># Sequences</th><th>Mean Entropy</th><th>Std Entropy</th></tr>
EOF

tail -n +2 "$OUTDIR/clustered_cluster_summary.tsv" | while IFS=$'\t' read -r cluster nseqs mean std; do
  echo "    <tr><td>$cluster</td><td>$nseqs</td><td>$mean</td><td>$std</td></tr>" >> "$HTML"
done

echo "  </table></div>" >> "$HTML"
fi

# Final Message
cat <<EOF >> "$HTML"
<div class="section">
  <h2>🎉 Report Complete</h2>
  <p>All figures and results generated by <strong>SignalSV</strong>.</p>
</div>
</body>
</html>
EOF

echo "[✔] Dashboard created: $HTML"


# chmod +x generate_dashboard.sh
# ./generate_dashboard.sh test_run_SignalSV
